# Codecov配置文件
# 文档: https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 3

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 75%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**/*_test.go"
  - "**/test/**"
  - "**/testutils/**"
  - "**/mock*.go"
  - "cmd/vman/main.go"
  - "scripts/**"
  - "docs/**"