[tool]
name = "protoc-gen-go"
description = "Protocol buffer compiler for Go"
homepage = "https://google.golang.org/protobuf"
repository = "https://github.com/protocolbuffers/protobuf-go"

[download]
type = "github"
repository = "protocolbuffers/protobuf-go"
asset_pattern = "protoc-gen-go.v{version}.{os}.{arch}.tar.gz"
extract_binary = "protoc-gen-go"

[download.arch_mapping]
"amd64" = "amd64"
"arm64" = "arm64"

[download.os_mapping]
"darwin" = "darwin"
"linux" = "linux"
"windows" = "windows"

[versions]
[versions.aliases]
latest = "1.34.2"
stable = "1.34.1"
# 添加用户需要的版本别名
v1_31_0 = "1.31.0"
legacy = "1.31.0"

[versions.constraints]
min_version = "1.25.0"