[tool]
name = "terraform"
description = "Infrastructure as Code tool"
homepage = "https://www.terraform.io/"
repository = "https://github.com/hashicorp/terraform"

[download]
type = "direct"
url_template = "https://releases.hashicorp.com/terraform/{version}/terraform_{version}_{os}_{arch}.zip"
extract_binary = "terraform"

[versions]
[versions.aliases]
latest = "1.7.0"
stable = "1.6.6"

[versions.constraints]
min_version = "1.0.0"