# vman 全局配置文件
version: "1.0"

# 全局设置
settings:
  # 下载设置
  download:
    timeout: 300s      # 下载超时时间
    retries: 3         # 重试次数
    concurrent_downloads: 2  # 并发下载数
  
  # 代理设置
  proxy:
    enabled: true       # 启用命令代理
    shims_in_path: true # 将shims目录添加到PATH
  
  # 日志设置
  logging:
    level: "info"       # 日志级别: debug, info, warn, error
    file: "~/.vman/logs/vman.log"  # 日志文件路径

# 全局工具版本
global_versions:
  # kubectl: "1.28.0"
  # terraform: "1.6.0"
  # sqlc: "1.20.0"

# 已注册的工具信息
tools:
  # kubectl:
  #   current_version: "1.28.0"
  #   installed_versions:
  #     - "1.28.0"
  #     - "1.29.0"